### PR TITLE
register official Pyblish guis as defaults

### PR DESCRIPTION
**Pull request by tokejepsen**
I wasn't entirely sure where to do this, so it up to debate.

### CODE REVIEW

**Comment by mottosso** [comment]
Could we put this in setup(), next to the other registrations taking place?

- https://github.com/pyblish/pyblish-maya/blob/master/pyblish_maya/lib.py#L39

We will also need the corresponding deregistration in teardown.

**Comment by tokejepsen** [comment]
Ahh, that makes sense:)

**Comment by mottosso** [comment]
Awesome. Now the next task is perhaps less interesting, but necessary nonetheless. :)

The message box is currently designed to show the user how to install a GUI. If they are installed per default, we'll need to account for pyblish-qml not showing up appropriately (as in, they haven't started it yet) and let the user know what they can do to remedy this.

**Comment by tokejepsen** [comment]
hmm, here's an interesting bug. I'm getting a maya crash (exists without any warning or anything), when running this code:

```python
import pyblish_maya

try:
    from pyblish_maya.vendor.Qt import QtWidgets, QtGui
except ImportError:
    raise ImportError("Pyblish requires either PySide or PyQt bindings.")

messagebox = QtWidgets.QMessageBox()
```

I was trying to provoke a message by not having ```pyblish-lite``` installed and ```pyblish-qml``` isn't running.

**Comment by tokejepsen** [comment]
Scratch that last comment, I had my environment wrong:s

**Comment by mottosso** [comment]
Ah yes that happens a little too easily, it's due to this:

- https://github.com/pyblish/pyblish-maya/issues/60

**Comment by mottosso** [comment]
Try adding this in `setup()`. It should always be in effect before any of the GUI's get a chance to load.

```python
os.environ["QT_PREFERRED_CHOICE"] = os.pathsep.join(["PySide", "PyQt4"])
```

- https://github.com/mottosso/Qt.py#override-preferred-choice

**Comment by mottosso** [comment]
Ok, so I'm growing a bit skeptical about this change.

I've had a look at how we could simplify these defaults on the QML side, by having it handle it's own failure with a friendly message. But the problem with that is that now pyblish-lite is no longer a fallback as pyblish-qml would be the only thing appearing to the user, and pyblish-qml could/should not directly refer anyone to pyblish-lite.

The reason I had a look at this, is because if we try and solve this just through pyblish-maya, then we will need special treatment for pyblish-qml as opposed to other GUIs which are simply checked for on the PYTHONPATH. For pyblish-qml, we would need to:

1. Check for it on the PYTHONPATH
2. If it is there, check that it is running in the background, if so all is well
3. If it is there, but not running in the background, wait the 1-2 seconds it takes to stop searching and carry with the next available GUI.

Special treatment *might* be ok, but it would break the now clean and uniform interface we've established with `pyblish.register_gui`.

However the 1-2 second delay is not ok. It would incur a permanent 1-2 second delay whenever a user attempts to show the GUI, unless we add additional special treatment to somehow remember what happened last time, and not try it again.

The downside of *that* is that there may/will be cases where the developer may have enabled another GUI through the environment (e.g. changing task directly in Maya) and would expect a new GUI to be picked up and therefore the environment to be re-checked.

And down the rabbit hole we go.

**Comment by tokejepsen** [comment]
When I publish from Maya with ```pyblish-qml``` on the ```PYTHONPATH```, I don't get a messagebox but this error message;
```
# Error: error: file C:\Users\admin\Documents\pipeline\src\pyblish-qml\pyblish_qml\host.py line 82: Is Pyblish QML running?

This GUI requires a separate, standalone process to be running
in the background in order to make use of it from within Maya
Make sure to run python -m pyblish_qml prior to showing it from
from Maya.

See the documentation for further information.
- https://github.com/pyblish/pyblish-qml

# # 
```

**Comment by tokejepsen** [comment]
Should we have an error handling similar to this;
```python
import pyblish_maya.lib
gui = pyblish_maya.lib._discover_gui()

try:
    gui()
except Exception as e:
    print e # messagebox with this error message
```

**Comment by tokejepsen** [comment]
Does pyblish-qml not know whether it's been started, meaning that it should be able to respond immediately about whether it's running or not?

**Comment by tokejepsen** [comment]
@mottosso are we deciding that the complexity involved outnumber the extra work for the end user?

**Comment by mottosso** [comment]
> Does pyblish-qml not know whether it's been started, meaning that it should be able to respond immediately about whether it's running or not?

It's like a web server, a client can try to request a new web page, but all it can really do is wait to get one back. It has no control over the server. In this case, all Maya can do is send a request into the abyss and hope someone sends something back. It cannot know whether anyone has received it, so it must wait and see.

The time it takes currently to try and call `proxy.show()` is about 2 seconds, that's how long it waits for a reply. It's possible that isn't enough for qml to answer, but at that point Maya assumes it's no there.

> @mottosso are we deciding that the complexity involved outnumber the extra work for the end user?

No one is deciding anything, but we should have a think about whether there is another way to achieve this goal (i.e. simplify for the user) with more grace. Clear documentation/installation instructions is one example.

**Comment by tokejepsen** [comment]
Closing this PR. Documentation is clearer for audience.

**Pull request closed without merging**
