### PR TITLE
Fix for #65

### LINKED ISSUE #65: Using multiple binding on "QT_PREFERRED_BINDING" errors.
**Description**

Setting multiple bindings on "QT_PREFERRED_BINDING" errors ```pyblish-maya/vendor/Qt.py``` with the following;

```
pyblish-maya: Could not load integration: Traceback (most recent call last):
  File "C:\Users\admin\Documents\conda-git-deployment\repositories\bumpybox-core\pyblish-maya\pyblish_maya\pythonpath\userSetup.py", line 3, in <module>
    __import__("pyblish_maya")
  File "C:\Users\admin\Documents\conda-git-deployment\repositories\bumpybox-core\pyblish-maya\pyblish_maya\__init__.py", line 3, in <module>
    from .lib import (
  File "C:\Users\admin\Documents\conda-git-deployment\repositories\bumpybox-core\pyblish-maya\pyblish_maya\lib.py", line 16, in <module>
    from .vendor.Qt import QtWidgets, QtGui
  File "C:\Users\admin\Documents\conda-git-deployment\repositories\bumpybox-core\pyblish-maya\pyblish_maya\vendor\Qt.py", line 237, in <module>
    _init()
  File "C:\Users\admin\Documents\conda-git-deployment\repositories\bumpybox-core\pyblish-maya\pyblish_maya\vendor\Qt.py", line 207, in _init
    "not available" % preferred)
ImportError: Preferred Qt binding "PySide;PySide2" not available
```

**Reproducible**

Before launching a ```pyblish-maya``` enabled Maya, set the following;

```python
os.environ["QT_PREFERRED_BINDING"] = "PySide" + os.pathsep + "PySide2"
```

### PR DESCRIPTION
**Pull request by tokejepsen**
Updating Qt.py to latest fixed #65.

### CODE REVIEW

**Comment by mottosso** [comment]
Ah, nice one. :)

**Comment by tokejepsen** [comment]
Does it look alright for merging?

**Comment by tokejepsen** [comment]
I'll bump version and release, of course :smile:

**Comment by mottosso** [comment]
Yes, looks good. Bump, merge and release!

**Pull request merged**
